name: Sync workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: pip install
        run: |
          pip install -r requirements.txt
      - name: execute py script 
        run: |
          pytest testing